### PR TITLE
Refactor HCRIS GeoJSON generation

### LINKED ISSUE #21: Review usa_hcris2018_facilitybedcounts_20200313_v1.ipynb
This notebook should be reviewed to ensure we're collecting data properly from HCRIS data. ~~Validating bed counts against other data sources as detailed in #12 can occur with this review.~~ (Deferring to a later PR) We can also refactor the notebook to create a v2 version that cleans things up if there is cleanup to do.

### PR DESCRIPTION
**Pull request by lossyrob**
Includes creating a new GeoJSON file that has only Provider Number so
that we can avoid re-geocoding the facilities.

Refactor changes some numbers from previous data, but that is
explainable via the fact that facilities have multiple records on file
and this method explicitly takes the most recent report.

Used this notebook to generate "usa_hospital_beds_hcris2018_v2.geojson"

TODO:
- [x] Check with #24 to see if this solves the notebook run issue there (I suspect that is not a regression)
- [x] ~~Validate numbers against other data sources~~ This will be done in a follow up

Fixes #21

### CODE REVIEW

**Comment by lossyrob** [comment]
Comparing the totals of AHD, the previous notebook version, and this version:

| Source | Total Staffed Beds count (all states & territories) |
|--------|----------|
[AHD.com](https://www.ahd.com/state_statistics.html) | 745,957
[Previous notebook](https://github.com/daveluo/covid19-healthsystemcapacity/blob/master/nbs/usa_hcris2018_facilitybedcounts_20200313_v1.ipynb) | 742,562
Refactored notebook | 743,588

**Comment by lossyrob** [comment]
See https://github.com/daveluo/covid19-healthsystemcapacity/issues/12#issuecomment-600395050 for validation results against https://www.kff.org/other/state-indicator/beds-by-ownership/?currentTimeframe=0&sortModel=%7B%22colId%22:%22Location%22,%22sort%22:%22asc%22%7D

**Comment by daveluo** [comment]
This looks great (much better than my v1)! I was able to successfully run everything in the docker jupyter env. 

Main thing is I noticed that the Fiscal End Year Date column was not a datetime dtype and thus not sorted correctly by date when we drop dups. Submitted a PR to fix this at https://github.com/lossyrob/covid19-healthsystemcapacity/pull/1

I also came across answers to the main questions we've raised about HCRIS data:

- **Why is HCRIS FY2019 data nearly empty?**
Probably because the cost reporting hasn't been completed by everyone yet. Per [Analyzing Hospital Medicare Cost Reports Using Base SAS](https://www.lexjansen.com/sesug/2018/SESUG2018_Paper-287_Final_PDF.pdf), the FY2019 reporting wouldn't expect to be 95% complete until March 31, 2021. We're just on the cusp of ~95% completion for FY2018:
>The cost report files are basically mature about 15 months after the year-end. For example, the 2016 cost report file was approximately 60% complete as of September 30, 2017; 90% complete as of December 31, 2017 and over 95% complete as of March 31, 2018.

- **Why are there sometimes multiple cost reports for a facility?**
>Hospitals submit an annual cost report, usually including twelve months of data, corresponding with their fiscal year (i.e. the 2017 hospital cost report file contains cost reports with a begin date between October 1, 2016 and September 30, 2017). Since hospitals usually submit one cost report per year, the MCR SAS files typically contain one record per hospital.
>Although hospitals generally submit one cost report per year, occasionally they submit multiple cost reports in a single year, typically under one of two scenarios: (1) each cost report covers part of the year or (2) the second submission replaces the first submission. Both scenarios result in records with duplicate provider numbers. Options for addressing such cases are discussed below:
> - The first scenario is due to hospitals submitting their data in partial year increments through separate report submissions in the same year. To identify such “short-period” cases, compute the report period using the variables for fiscal year begin date (FY_BGN_DT) and fiscal year end date (FY_END_DT). Two options for handling this scenario follow:
>   - Combine the reports, summing the appropriate fields, such as costs and revenue, to obtain a full year of data. Be cautious not to add certain numeric fields such as beds and FTEs since they are not meant to be accumulated.
>  - Because very few providers submit partial years, simplify the process, only keeping selfdefined full year” cost reports. For our purposes, we define a “full year” as having ten to fourteen months. (Note: Reports covering more than twelve months of data are rare, but possible.)
>  - The second scenario is often a result of a hospital updating or correcting the data initially reported. When this happens, it is common to use the most recently submitted (and likely most up-to-date) report and drop the old report to avoid double counting. The code below subsets your file only keeping reports with a “full year” of data (self-defined as 10-14 months of data), using the fiscal year begin date and end date variables.

One other reason looks like if there's a change of control for the facility (see `Provider Control Type Code`), they may be submitting a new cost report:
Screen Shot 2020-03-18 at 12 13 39 AM

So I think we're good with the approach to take the most recent (last) report when there are multiple for a facility.

**Comment by lossyrob** [comment]
Merged in fix and cleared output, so this should be good to go!

**Pull request merged**
